In [1]:
import sys
sys.path.append('/home/azureuser/prathyusha/')
from utils import *
spark = instantiate_spark_sedona("50g")

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Warning: Ignoring non-Spark config property: fs.azure.account.auth.type.propheusdatabay.dfs.core.windows.net
Warning: Ignoring non-Spark config property: fs.azure.account.oauth2.msi.tenant
Warning: Ignoring non-Spark config property: fs.azure.account.oauth2.use.metadata.header
Warning: Ignoring non-Spark config property: sedona.global.indextype
Warning: Ignoring non-Spark config property: fs.azure.account.oauth2.client.endpoint
Warning: Ignoring non-Spark config property: fs.azure.account.oauth2.client.id
Warning: Ignoring non-Spark config property: fs.azure.account.oauth.provider.type.propheusdatabay.dfs.core.windows.net
Warning: Ignoring non-Spark config property: fs.azure.account.oauth2.msi.endpoint
Warning: Ignoring non-Spark config property: sedona.global.index
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.

Spark Session and SedonaContext have been successfully initiated.

In [2]:
from pyspark.sql.functions import *

final_df = spark.read.parquet("abfss://propheus-data-science@propheusdatabay.dfs.core.windows.net/Thailand/thailand_quadkeys/Quadkey_pop_hh_estimated_updated")
final_df_req = final_df.filter(~col('adm1_name').isin('bangkok', 'nonthaburi', 'pathumthani', 'samutprakan', 'samutsakhon', 'nakhonpathom'))
final_df_req.show()

+----------------+------------+--------------------+------------------+-----------------------+------------------+--------------------+---------------+
|         quadkey|   adm1_name|Pop_nso_to_hdx_ratio|   hdx_Quadkey_Pop|nso_adjusted_population|sum_floor_area_sqm|Qk_pop_to_hh_sampled|Qk_estimated_hh|
+----------------+------------+--------------------+------------------+-----------------------+------------------+--------------------+---------------+
|1322121030100010|amnatcharoen|  1.3095653425533569| 142.0465920000001|     186.01929391101703| 76090.12173170949|   2.449373527632673|           76.0|
|1322121021232330|amnatcharoen|  1.3095653425533569|201.32532000000032|      263.6486616504646| 62566.12192884956|   2.488199875170112|          106.0|
|1322121030102232|amnatcharoen|  1.3095653425533569|135.38815800000015|     177.29963950893818| 54976.98828964075|   2.523829708720109|           70.0|
|1322121021312003|amnatcharoen|  1.3095653425533569|199.33478199999976|      261.0419220726284|39048.393217160105|   2.584033375337401|          101.0|
|1322121021320211|amnatcharoen|  1.3095653425533569|206.67024000000035|      270.6481836411849|  35996.1548019615|  2.5993003458279236|          104.0|
|1322121030122012|amnatcharoen|  1.3095653425533569|145.37580900000006|     190.37912111205645|29723.622049337184|   2.628157947004023|           72.0|
|1322121021031120|amnatcharoen|  1.3095653425533569|156.30782800000023|      204.6953143185915|  24394.4598374712|   2.658421756800076|           77.0|
|1322121012212023|amnatcharoen|  1.3095653425533569|187.04133199999967|      244.9428460122157|  23984.0069129313|  2.6628325291990502|           92.0|
|1322121003230310|amnatcharoen|  1.3095653425533569|145.62649500000032|     190.70741080952013|22197.792230699935|  2.6724366749136674|           71.0|
|1322121032001310|amnatcharoen|  1.3095653425533569|        153.530104|      201.0577032370125| 21368.81329576046|   2.676445088045084|           75.0|
|1322121003321221|amnatcharoen|  1.3095653425533569| 55.47675999999998|      72.65044221315034|21312.500805710653|  2.6781066740818553|           27.0|
|1322121021102131|amnatcharoen|  1.3095653425533569|133.61798200000018|     174.98147836911852|19010.644737653933|   2.692999244810911|           65.0|
|1322121030232213|amnatcharoen|  1.3095653425533569|110.71882500000011|     144.99353598823032|18818.998939166482|  2.6963646193380084|           54.0|
|1322121012102112|amnatcharoen|  1.3095653425533569|63.047640000000094|      82.56500427378084|18386.909721322038|   2.698633187580349|           31.0|
|1322121021102302|amnatcharoen|  1.3095653425533569|117.23087100000016|      153.5214857389436|17937.011636914584|   2.701748651924802|           57.0|
|1322121021210210|amnatcharoen|  1.3095653425533569|155.00268000000005|     202.98613773088843|16809.720638548195|  2.7134730050527254|           75.0|
|1322121021030221|amnatcharoen|  1.3095653425533569| 141.1812640000002|     184.88609035227617| 16590.91976926189|  2.7147661011193303|           68.0|
|1322121021320103|amnatcharoen|  1.3095653425533569| 86.27923399999993|     112.98829462845114|13913.828257351171|  2.7411080829403747|           41.0|
|1322121021102300|amnatcharoen|  1.3095653425533569| 95.80157200000012|     125.45841845333024| 13755.01939547425|     2.7416409805423|           46.0|
|1322121021122331|amnatcharoen|  1.3095653425533569|  83.1961020000001|     108.95073181473414|11797.261507742904|   2.758863431206768|           39.0|
+----------------+------------+--------------------+------------------+-----------------------+------------------+--------------------+---------------+
only showing top 20 rows

In [3]:
mapping = spark.read.parquet("abfss://propheus-data-science@propheusdatabay.dfs.core.windows.net/Thailand/thailand_quadkeys/thailand_quadkeys_w_subdistrict")
mapping.show()

+----------------+--------------------+--------------------+-----------------+------------+---------+--------------------+
|         quadkey|    quadkey_geometry|    quadkey_centroid|        adm3_name|   adm2_name|adm1_name|            geometry|
+----------------+--------------------+--------------------+-----------------+------------+---------+--------------------+
|1322122012022123|POLYGON ((101.980...|POINT (101.983337...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022132|POLYGON ((101.986...|POINT (101.988830...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022133|POLYGON ((101.991...|POINT (101.994323...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023022|POLYGON ((101.997...|POINT (101.999816...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023023|POLYGON ((102.002...|POINT (102.005310...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023020|POLYGON ((101.997...|POINT (101.999816...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023021|POLYGON ((102.002...|POINT (102.005310...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023030|POLYGON ((102.008...|POINT (102.010803...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023120|POLYGON ((102.019...|POINT (102.021789...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023121|POLYGON ((102.024...|POINT (102.027282...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023130|POLYGON ((102.030...|POINT (102.032775...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023102|POLYGON ((102.019...|POINT (102.021789...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023103|POLYGON ((102.024...|POINT (102.027282...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023100|POLYGON ((102.019...|POINT (102.021789...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023101|POLYGON ((102.024...|POINT (102.027282...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012023110|POLYGON ((102.030...|POINT (102.032775...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022130|POLYGON ((101.986...|POINT (101.988830...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022131|POLYGON ((101.991...|POINT (101.994323...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022103|POLYGON ((101.980...|POINT (101.983337...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
|1322122012022112|POLYGON ((101.986...|POINT (101.988830...|Thung Mahacharoen|Wang Nam Yen|  Sa Kaeo|POLYGON ((102.032...|
+----------------+--------------------+--------------------+-----------------+------------+---------+--------------------+
only showing top 20 rows

In [4]:
final_df_joined = final_df_req.select('quadkey', 'nso_adjusted_population', 'Qk_pop_to_hh_sampled').join(
    mapping.select('quadkey', 'adm2_name', 'adm3_name', 'adm1_name'),
    on = 'quadkey',
    how = 'inner'
)
final_df_joined.count()

960076

In [5]:
final_df_joined.show()

+----------------+-----------------------+--------------------+-------------------+------------+------------+
|         quadkey|nso_adjusted_population|Qk_pop_to_hh_sampled|          adm2_name|   adm3_name|   adm1_name|
+----------------+-----------------------+--------------------+-------------------+------------+------------+
|1322010330330112|       3.85783809004375|  3.0752889070291864|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010330331231|      4.590031058358725|   3.514785880528593|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331201320|      2.149387830642142|   3.665291787562955|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331201323|     3.1295666306991308|   2.997189388366925|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331202200|       9.18006211671745|   2.760167183741254|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331202212|      4.360529505440788|     2.9530662261496|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331221231|     13.770093175076175|  2.8000618690918384|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331222012|      3.089849985643525|  3.3434753253878804|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331222202|     6.8850465875380875|   2.810651533899183|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331223230|      4.590031058358725|   2.693749597541494|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010331231230|      2.754018635015235|  3.0728912928448313|         Pang Mapha|  Pang Mapha|Mae Hong Son|
|1322010331232100|      5.355036234751846|   2.965004625512987|         Pang Mapha|  Pang Mapha|Mae Hong Son|
|1322010331232322|     3.1295666306991308|   3.419025684265097|         Pang Mapha|  Pang Mapha|Mae Hong Son|
|1322010331233130|     2.2950155291793624|   2.981101646070361|         Pang Mapha|  Pang Mapha|Mae Hong Son|
|1322010331333201|      7.480521990072338|  2.7790031827669606|                Pai|Mae Na Toeng|Mae Hong Son|
|1322010332031102|     2.9730118937083216|   3.193795237483947|Mueang Mae Hong Son| Mok Champae|Mae Hong Son|
|1322010332031121|     1.8581324335677012|  3.0561952004875286|Mueang Mae Hong Son| Mok Champae|Mae Hong Son|
|1322010332102311|      9.755195276230431|  2.8227852170986254|Mueang Mae Hong Son| Mok Champae|Mae Hong Son|
|1322010332111231|     3.2664798648577835|  3.3327232070900528|         Pang Mapha|   Na Pu Pom|Mae Hong Son|
|1322010332112020|     20.439456769244707|   2.871865060729804|Mueang Mae Hong Son|    Huai Pha|Mae Hong Son|
+----------------+-----------------------+--------------------+-------------------+------------+------------+
only showing top 20 rows

In [6]:
district_level_nso_pop = final_df_joined.groupBy('adm1_name', 'adm2_name').agg(
    sum('nso_adjusted_population').alias('nso_adjusted_hdx_population')
)
district_level_nso_pop.show()

+-------------------+-----------------+---------------------------+
|          adm1_name|        adm2_name|nso_adjusted_hdx_population|
+-------------------+-----------------+---------------------------+
|         Chiang Rai|          Pa Daet|         24578.121527529765|
|                Nan|        Santi Suk|           13083.5321560293|
|     Kamphaeng Phet|  Pang Sila Thong|         27757.451102276405|
|      Maha Sarakham|     Yang Sisurat|         28337.108878189585|
|           Saraburi|         Nong Don|         14834.771568171083|
|   Nong Bua Lam Phu|         Na Klang|          90339.88305616786|
|  Nakhon Ratchasima|      Chum Phuang|          79499.40946119936|
|           Buri Ram|    Non Din Daeng|          19530.01458633106|
|             Roi Et|        Nong Phok|          51058.00226440467|
|   Ubon Ratchathani|      Khong Chiam|         30983.471244773307|
|   Ubon Ratchathani|        Buntharik|           83897.8993857903|
|Nakhon Si Thammarat|      Pak Phanang|          111256.9609846058|
|Nakhon Si Thammarat|Chaloem Phra Kiat|           34222.3559938192|
|         Chiang Rai|     Mae Fa Luang|         58906.877193712484|
|       Kanchanaburi|   Thong Pha Phum|         48021.867434453874|
|           Saraburi|       Nong Saeng|          33262.50019837475|
|       Chachoengsao|   Bang Nam Priao|         119705.37574343859|
|          Khon Kaen|         Ban Phai|         102877.61086040964|
|            Kalasin|       Yang Talat|          97241.39926953414|
|             Roi Et|      Suwannaphum|          92101.88161089421|
+-------------------+-----------------+---------------------------+
only showing top 20 rows

In [7]:
district_level_nso_pop.count()

848

In [8]:
district_truth_set = spark.read.csv('Population Adjustment - Districts - Final_District_Adjustments.csv', header=True)
district_truth_set = district_truth_set.select('Province', 'District', 'Population - Truth set (nso matched)')
district_truth_set.show()

+-----------------+-------------------+------------------------------------+
|         Province|           District|Population - Truth set (nso matched)|
+-----------------+-------------------+------------------------------------+
|       Udon Thani|          Thung Fon|                         24593.84085|
|Nakhon Ratchasima|              Khong|                         80640.37428|
|         Lop Buri|    Mueang Lop Buri|                         248302.4556|
|        Khon Kaen|          Chum Phae|                         120085.3787|
|      Suphan Buri|            U Thong|                         97047.32322|
|              Nan|             Na Noi|                         31401.04129|
|     Kanchanaburi|          Tha Muang|                         105003.4113|
|      Surat Thani|          Phrasaeng|                         72105.59717|
|          Bangkok|          Lat Phrao|                         246192.3001|
|     Kanchanaburi|           Tha Maka|                         128199.0563|
|        Khon Kaen|           Ban Phai|                         101279.5832|
|     Mae Hong Son|Mueang Mae Hong Son|                         46133.65425|
| Ubon Ratchathani|           Nam Yuen|                         67809.83014|
|         Lop Buri|         Lam Sonthi|                         25336.15528|
|Nakhon Ratchasima|      Dan Khun Thot|                          124492.983|
| Ubon Ratchathani|      Don Mot Daeng|                         26181.21309|
| Nong Bua Lam Phu|           Na Klang|                         90339.88306|
|          Bangkok|        Huai Khwang|                         244638.6819|
|       Nonthaburi|           Bang Yai|                         221165.6765|
|Nakhon Ratchasima|             Sikhio|                         119566.3839|
+-----------------+-------------------+------------------------------------+
only showing top 20 rows

In [9]:
multiplier_join = district_level_nso_pop.join(
    district_truth_set,
    ((district_level_nso_pop.adm1_name == district_truth_set.Province) &
    (district_level_nso_pop.adm2_name == district_truth_set.District)),
    how = 'inner'
).drop(district_truth_set.Province, district_truth_set.District)

multiplier_join = multiplier_join.withColumn("Multiplier", col('Population - Truth set (nso matched)')/col('nso_adjusted_hdx_population'))
multiplier_join.show()

+-------------------+-----------------+---------------------------+------------------------------------+------------------+
|          adm1_name|        adm2_name|nso_adjusted_hdx_population|Population - Truth set (nso matched)|        Multiplier|
+-------------------+-----------------+---------------------------+------------------------------------+------------------+
|         Chiang Rai|          Pa Daet|         24578.121527529765|                         24026.71372| 0.977565095570378|
|                Nan|        Santi Suk|           13083.5321560293|                         12634.08971|0.9656482331629244|
|     Kamphaeng Phet|  Pang Sila Thong|         27757.451102276405|                         28631.35473| 1.031483569024532|
|      Maha Sarakham|     Yang Sisurat|         28337.108878189585|                         27431.15232|0.9680293228895035|
|           Saraburi|         Nong Don|         14834.771568171083|                         15502.00202|1.0449774672136172|
|   Nong Bua Lam Phu|         Na Klang|          90339.88305616786|                         90339.88306| 1.000000000042419|
|  Nakhon Ratchasima|      Chum Phuang|          79499.40946119936|                         78680.65329|0.9897011037346263|
|           Buri Ram|    Non Din Daeng|          19530.01458633106|                         23944.17811|1.2260194688619632|
|             Roi Et|        Nong Phok|          51058.00226440467|                         61240.96606|1.1994391347875832|
|   Ubon Ratchathani|      Khong Chiam|         30983.471244773307|                         30961.11173|0.9992783405514294|
|   Ubon Ratchathani|        Buntharik|           83897.8993857903|                         83837.35369|0.9992783407423363|
|Nakhon Si Thammarat|      Pak Phanang|          111256.9609846058|                          100562.126|0.9038726665733248|
|Nakhon Si Thammarat|Chaloem Phra Kiat|           34222.3559938192|                         35423.22807|1.0350902806457185|
|         Chiang Rai|     Mae Fa Luang|         58906.877193712484|                         74747.55991|1.2689105834654275|
|       Kanchanaburi|   Thong Pha Phum|         48021.867434453874|                         68781.19539|1.4322890604760632|
|           Saraburi|       Nong Saeng|          33262.50019837475|                         16566.02779| 0.498039163959462|
|       Chachoengsao|   Bang Nam Priao|         119705.37574343859|                         104310.9859| 0.871397673263789|
|          Khon Kaen|         Ban Phai|         102877.61086040964|                         101279.5832|0.9844667110069465|
|            Kalasin|       Yang Talat|          97241.39926953414|                         109147.3052| 1.122436596140138|
|             Roi Et|      Suwannaphum|          92101.88161089421|                         85331.44032|0.9264896528444715|
+-------------------+-----------------+---------------------------+------------------------------------+------------------+
only showing top 20 rows

In [10]:
multiplier_join.count()

848

In [13]:
edge_cases = multiplier_join.filter(col('Multiplier')>2)
edge_cases.show()

+-----------------+-----------------+---------------------------+------------------------------------+-----------------+
|        adm1_name|        adm2_name|nso_adjusted_hdx_population|Population - Truth set (nso matched)|       Multiplier|
+-----------------+-----------------+---------------------------+------------------------------------+-----------------+
|        Khon Kaen|        Wiang Kao|         136.91516442371127|                          26580.6012|194.1392051923557|
|Nakhon Ratchasima|Chaloem Phra Kiat|          9469.327622144923|                         32809.58129|3.464826923220153|
|      Suphan Buri|        Don Chedi|          46262.48569254694|                         202022.3353|4.366871608296364|
|           Rayong|      Pluak Daeng|          67810.26054058631|                         161836.9948| 2.38661514510973|
+-----------------+-----------------+---------------------------+------------------------------------+-----------------+

In [12]:
# multiplier_join_adm1_adm2
# multiplier_join.toPandas().to_csv('multiplier_join_adm1_adm2.csv', index=False)

In [14]:
Matchinh_truth_set = multiplier_join.select('adm1_name', 'adm2_name', 'Multiplier').join(
    edge_cases,
    on = ['adm1_name', 'adm2_name'],
    how = 'left_anti'
).join(
    final_df_joined,
    on = ['adm1_name', 'adm2_name'],
    how = 'inner'
)
Matchinh_truth_set = Matchinh_truth_set.withColumn("Truthset_adjusted_population", col('Multiplier')*col('nso_adjusted_population'))
Matchinh_truth_set = Matchinh_truth_set.withColumn("Truthset_estimated_HH_count", col('Truthset_adjusted_population')/col('Qk_pop_to_hh_sampled'))
Matchinh_truth_set.show()

+---------+------------+------------------+----------------+-----------------------+--------------------+--------------+----------------------------+---------------------------+
|adm1_name|   adm2_name|        Multiplier|         quadkey|nso_adjusted_population|Qk_pop_to_hh_sampled|     adm3_name|Truthset_adjusted_population|Truthset_estimated_HH_count|
+---------+------------+------------------+----------------+-----------------------+--------------------+--------------+----------------------------+---------------------------+
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132122213|      5.992985136861609|   3.644070569137187|Nong Hua Chang|            6.77997079801581|          1.860548710400281|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132123212|      5.778315295107728|   3.681289655698566|Nong Hua Chang|           6.537110983571455|         1.7757665369939395|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132132302|      4.770791281866241|   3.642787803275275|     Si Samran|           5.397281127151318|         1.4816347859456862|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132300033|     2.1468560768398084|  3.4598440597765916|Nong Hua Chang|          2.4287765072180934|         0.7019901663934888|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132300110|     3.3736309778911275|    3.80663376992701|Nong Hua Chang|           3.816648797057004|          1.002630940546242|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132300111|     2.7909128998917514|  3.8488426155627384|Nong Hua Chang|          3.1574094593835222|         0.8203529670495187|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132302103|      6.057244237521151|  3.4600294859176324|Nong Hua Chang|           6.852668262806555|          1.980523082446843|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132302312|     12.881136461038853|  3.4057221514553224|Nong Hua Chang|          14.572659043308564|           4.27887490383836|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132310130|      2.862474769119745|   3.964962972680199|     Si Samran|          3.2383686762907917|         0.8167462593230094|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132310310|     2.1468560768398084|  3.8255639691120527|     Si Samran|          2.4287765072180934|         0.6348806416068985|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132312012|     2.1468560768398084|   3.713016932474843|     Si Samran|          2.4287765072180934|         0.6541248131608268|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132312300|      3.864340938311656|   3.529461682031764|     Si Samran|           4.371797712992569|         1.2386585000338939|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132312303|      4.293712153679617|   3.761110884673769|   Don Ya Nang|           4.857553014436187|         1.2915208201466044|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132312332|      4.293712153679617|   3.837093882825779|   Don Ya Nang|           4.857553014436187|          1.265945833688829|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132313102|       5.35167449582964|  3.5543071919030895|       Pa Faek|           6.054444650468824|         1.7034106292954045|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132313222|     130.95822068722822|  3.0588294262014957|    Si Chomphu|           148.1553669403036|          48.43531504935381|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132313230|      6.440568230519426|  3.5193894865699074|   Don Ya Nang|           7.286329521654281|         2.0703390600725284|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132313303|     3.7459512085626065|   3.673465948508351|       Pa Faek|           4.237861303648514|         1.1536411016330073|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132321022|      4.293712153679617|  3.8039727592927886|Nong Hua Chang|           4.857553014436187|         1.2769684016715392|
|Bueng Kan|Phon Charoen|1.1313178062654645|1322102132321102|      68.69939445887384|  3.2076964107209713|   Don Ya Nang|           77.72084823097896|         24.229490038775268|
+---------+------------+------------------+----------------+-----------------------+--------------------+--------------+----------------------------+---------------------------+
only showing top 20 rows

In [33]:
buildings = spark.read.parquet("abfss://propheus-data-science@propheusdatabay.dfs.core.windows.net/Thailand/Gee_Buildings/buildings_full_dataset_with_quadkey_with_floor_area.parquet")
buildings = buildings.drop('province_en', 'district_en', 'tambon_en').join(
    mapping,
    on = 'quadkey',
    how = 'inner'
)

# buildings.count()
buildings_req = buildings.join(
    edge_cases.select(col('adm1_name'), col('adm2_name')),
    on = ['adm1_name', 'adm2_name'],
    how = 'inner'
)
buildings_req_qkey_grouped = buildings_req.groupby('quadkey').agg(count('*').alias('Buil_in_quadkey'))
buildings_req_qkey_grouped.show()

+----------------+---------------+
|         quadkey|Buil_in_quadkey|
+----------------+---------------+
|1322102233220033|            298|
|1322102233222203|              3|
|1322102232313330|              3|
|1322102232331023|              4|
|1322102232332230|              3|
|1322102232333120|             89|
|1322102233220200|              7|
|1322102232331033|             25|
|1322102232333133|             38|
|1322102232333102|             88|
|1322102233202231|              5|
|1322120010110013|              1|
|1322102232331012|              4|
|1322102232330301|              2|
|1322102233220202|              6|
|1322120010111032|              1|
|1322102232330133|             10|
|1322102232331103|             77|
|1322102232331220|             11|
|1322102232333112|             38|
+----------------+---------------+
only showing top 20 rows

In [44]:
Matchinh_truth_set_edge_cases = multiplier_join.select('adm1_name', 'adm2_name', 'Multiplier').join(
    edge_cases,
    on = ['adm1_name', 'adm2_name'],
    how = 'inner'
).join(
    final_df_joined,
    on = ['adm1_name', 'adm2_name'],
    how = 'inner'
).join(
    buildings_req_qkey_grouped,
    on = 'quadkey',
    how = 'inner'
)
Matchinh_truth_set_edge_cases.show()

+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+
|         quadkey|adm1_name|adm2_name|       Multiplier|nso_adjusted_hdx_population|Population - Truth set (nso matched)|       Multiplier|nso_adjusted_population|Qk_pop_to_hh_sampled|           adm3_name|Buil_in_quadkey|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+
|1322102233220033|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.407084425025908|            Khao Noi|            298|
|1322102233222203|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.163964428316886|Mueang Kao Phatthana|              3|
|1322102232313330|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.1350319716847506|          Nai Mueang|              3|
|1322102232331023|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.033065413446324|          Nai Mueang|              4|
|1322102232332230|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.1742984160659775|Mueang Kao Phatthana|              3|
|1322102232333120|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.6085515696162465|          Nai Mueang|             89|
|1322102233220200|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.0743985279221886|          Nai Mueang|              7|
|1322102232331033|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.718648251949324|          Nai Mueang|             25|
|1322102232333133|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.7349800443514987|Mueang Kao Phatthana|             38|
|1322102232333102|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.609223636967238|          Nai Mueang|             88|
|1322102233202231|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.052843852333077|            Khao Noi|              5|
|1322120010110013|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.248512228487311|Mueang Kao Phatthana|              1|
|1322102232331012|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.031918597036763|          Nai Mueang|              4|
|1322102232330301|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.199801773382734|          Nai Mueang|              2|
|1322102233220202|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.002704136129589|          Nai Mueang|              6|
|1322120010111032|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|       6.41253635491577|  3.4640234843809994|Mueang Kao Phatthana|              1|
|1322102232330133|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.8421350686635294|          Nai Mueang|             10|
|1322102232331103|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.5991016664491293|          Nai Mueang|             77|
|1322102232331220|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.8353976760583333|          Nai Mueang|             11|
|1322102232333112|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.6882466704741703|          Nai Mueang|             38|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+
only showing top 20 rows

In [43]:
Matchinh_truth_set_edge_cases.columns

['quadkey',
 'adm1_name',
 'adm2_name',
 'Multiplier',
 'Population - Truth set (nso matched)',
 'nso_adjusted_hdx_population',
 'Population - Truth set (nso matched)',
 'Multiplier',
 'nso_adjusted_population',
 'Qk_pop_to_hh_sampled',
 'adm3_name',
 'Buil_in_quadkey',
 'Buil_in_district']

In [45]:
from pyspark.sql.window import Window

w = Window.partitionBy('adm1_name', 'adm2_name')

Matchinh_truth_set_edge_cases = Matchinh_truth_set_edge_cases.withColumn(
    "Buil_in_district", count("*").over(w)
)


Matchinh_truth_set_edge_cases = Matchinh_truth_set_edge_cases.withColumn("Truthset_adjusted_population", col('Population - Truth set (nso matched)')*col('Buil_in_quadkey')/col('Buil_in_district'))
Matchinh_truth_set_edge_cases = Matchinh_truth_set_edge_cases.withColumn("Truthset_estimated_HH_count", col('Truthset_adjusted_population')/col('Qk_pop_to_hh_sampled'))

Matchinh_truth_set_edge_cases.show()

+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|         quadkey|adm1_name|adm2_name|       Multiplier|nso_adjusted_hdx_population|Population - Truth set (nso matched)|       Multiplier|nso_adjusted_population|Qk_pop_to_hh_sampled|           adm3_name|Buil_in_quadkey|Buil_in_district|Truthset_adjusted_population|Truthset_estimated_HH_count|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|1322102233220033|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.407084425025908|            Khao Noi|            298|             392|            20206.6815244898|          8394.670878347904|
|1322102233222203|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.163964428316886|Mueang Kao Phatthana|              3|             392|          203.42296836734693|          64.29369639770589|
|1322102232313330|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.1350319716847506|          Nai Mueang|              3|             392|          203.42296836734693|          64.88704747021397|
|1322102232331023|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.033065413446324|          Nai Mueang|              4|             392|           271.2306244897959|          89.42458784019755|
|1322102232332230|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.1742984160659775|Mueang Kao Phatthana|              3|             392|          203.42296836734693|          64.08438706889328|
|1322102232333120|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.6085515696162465|          Nai Mueang|             89|             392|            6034.88139489796|          2313.498979736779|
|1322102233220200|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  3.0743985279221886|          Nai Mueang|              7|             392|           474.6535928571429|          154.3890905965058|
|1322102232331033|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.718648251949324|          Nai Mueang|             25|             392|          1695.1914030612245|          623.5420127799686|
|1322102232333133|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.7349800443514987|Mueang Kao Phatthana|             38|             392|          2576.6909326530613|          942.1242169479998|
|1322102232333102|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   2.609223636967238|          Nai Mueang|             88|             392|           5967.073738775511|         2286.9154081829415|
|1322102233202231|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.052843852333077|            Khao Noi|              5|             392|           339.0382806122449|         111.05654170721552|
|1322120010110013|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.248512228487311|Mueang Kao Phatthana|              1|             392|           67.80765612244898|         20.873449552635364|
|1322102232331012|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.031918597036763|          Nai Mueang|              4|             392|           271.2306244897959|           89.4584124899931|
|1322102232330301|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.199801773382734|          Nai Mueang|              2|             392|          135.61531224489795|         42.382410489612774|
|1322102233220202|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|   3.002704136129589|          Nai Mueang|              6|             392|          406.84593673469385|         135.49318157569402|
|1322120010111032|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|       6.41253635491577|  3.4640234843809994|Mueang Kao Phatthana|              1|             392|           67.80765612244898|         19.574825756288373|
|1322102232330133|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.8421350686635294|          Nai Mueang|             10|             392|           678.0765612244898|          238.5799917466079|
|1322102232331103|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.5991016664491293|          Nai Mueang|             77|             392|           5221.189521428571|          2008.843897423111|
|1322102232331220|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.8353976760583333|          Nai Mueang|             11|             392|           745.8842173469388|          263.0615887305938|
|1322102232333112|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|                    0.0|  2.6882466704741703|          Nai Mueang|             38|             392|          2576.6909326530613|          958.5024175622127|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
only showing top 20 rows

In [48]:
Matchinh_truth_set_edge_cases.filter(col('quadkey') == '1322120010111102').show()
Matchinh_truth_set_edge_cases.filter(col('quadkey') == '1322102232332333').show()

+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|         quadkey|adm1_name|adm2_name|       Multiplier|nso_adjusted_hdx_population|Population - Truth set (nso matched)|       Multiplier|nso_adjusted_population|Qk_pop_to_hh_sampled|           adm3_name|Buil_in_quadkey|Buil_in_district|Truthset_adjusted_population|Truthset_estimated_HH_count|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|1322120010111102|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|     13.792182954314761|  3.0703623039123156|Mueang Kao Phatthana|              3|             392|          203.42296836734693|          66.25373432579647|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+

+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|         quadkey|adm1_name|adm2_name|       Multiplier|nso_adjusted_hdx_population|Population - Truth set (nso matched)|       Multiplier|nso_adjusted_population|Qk_pop_to_hh_sampled|           adm3_name|Buil_in_quadkey|Buil_in_district|Truthset_adjusted_population|Truthset_estimated_HH_count|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+
|1322102232332333|Khon Kaen|Wiang Kao|194.1392051923557|         136.91516442371127|                          26580.6012|194.1392051923557|      6.316959825996866|   3.268238428284067|Mueang Kao Phatthana|              3|             392|          203.42296836734693|         62.242389235399415|
+----------------+---------+---------+-----------------+---------------------------+------------------------------------+-----------------+-----------------------+--------------------+--------------------+---------------+----------------+----------------------------+---------------------------+

In [49]:
Matchinh_truth_set_edge_cases_final = Matchinh_truth_set_edge_cases.select('adm1_name', 'adm2_name', 'adm3_name', 'quadkey', 'Truthset_estimated_HH_count').withColumnRenamed(
    'Truthset_estimated_HH_count' , 'HH_Count'
)
Matchinh_truth_set_edge_cases_final.show()

+---------+---------+--------------------+----------------+------------------+
|adm1_name|adm2_name|           adm3_name|         quadkey|          HH_Count|
+---------+---------+--------------------+----------------+------------------+
|Khon Kaen|Wiang Kao|            Khao Noi|1322102233220033| 8394.670878347904|
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322102233222203| 64.29369639770589|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232313330| 64.88704747021397|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232331023| 89.42458784019755|
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322102232332230| 64.08438706889328|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232333120| 2313.498979736779|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102233220200| 154.3890905965058|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232331033| 623.5420127799686|
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322102232333133| 942.1242169479998|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232333102|2286.9154081829415|
|Khon Kaen|Wiang Kao|            Khao Noi|1322102233202231|111.05654170721552|
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322120010110013|20.873449552635364|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232331012|  89.4584124899931|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232330301|42.382410489612774|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102233220202|135.49318157569402|
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322120010111032|19.574825756288373|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232330133| 238.5799917466079|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232331103| 2008.843897423111|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232331220| 263.0615887305938|
|Khon Kaen|Wiang Kao|          Nai Mueang|1322102232333112| 958.5024175622127|
+---------+---------+--------------------+----------------+------------------+
only showing top 20 rows

In [50]:
Matchinh_truth_set_71 = Matchinh_truth_set.select('adm1_name', 'adm2_name', 'adm3_name', 'quadkey', 'Truthset_estimated_HH_count').withColumnRenamed(
    'Truthset_estimated_HH_count' , 'HH_Count'
).unionByName(Matchinh_truth_set_edge_cases_final)


Matchinh_truth_set_71.show()

+---------+------------+--------------+----------------+------------------+
|adm1_name|   adm2_name|     adm3_name|         quadkey|          HH_Count|
+---------+------------+--------------+----------------+------------------+
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132122213| 1.860548710400281|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132123212|1.7757665369939395|
|Bueng Kan|Phon Charoen|     Si Samran|1322102132132302|1.4816347859456862|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132300033|0.7019901663934888|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132300110| 1.002630940546242|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132300111|0.8203529670495187|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132302103| 1.980523082446843|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132302312|  4.27887490383836|
|Bueng Kan|Phon Charoen|     Si Samran|1322102132310130|0.8167462593230094|
|Bueng Kan|Phon Charoen|     Si Samran|1322102132310310|0.6348806416068985|
|Bueng Kan|Phon Charoen|     Si Samran|1322102132312012|0.6541248131608268|
|Bueng Kan|Phon Charoen|     Si Samran|1322102132312300|1.2386585000338939|
|Bueng Kan|Phon Charoen|   Don Ya Nang|1322102132312303|1.2915208201466044|
|Bueng Kan|Phon Charoen|   Don Ya Nang|1322102132312332| 1.265945833688829|
|Bueng Kan|Phon Charoen|       Pa Faek|1322102132313102|1.7034106292954045|
|Bueng Kan|Phon Charoen|    Si Chomphu|1322102132313222| 48.43531504935381|
|Bueng Kan|Phon Charoen|   Don Ya Nang|1322102132313230|2.0703390600725284|
|Bueng Kan|Phon Charoen|       Pa Faek|1322102132313303|1.1536411016330073|
|Bueng Kan|Phon Charoen|Nong Hua Chang|1322102132321022|1.2769684016715392|
|Bueng Kan|Phon Charoen|   Don Ya Nang|1322102132321102|24.229490038775268|
+---------+------------+--------------+----------------+------------------+
only showing top 20 rows

In [51]:
Matchinh_truth_set_71.count()

960076

In [15]:


Matchinh_truth_set_71.filter(col('quadkey') == '1322120010111102').show()

[Stage 120:======================================================>(98 + 1) / 99]

+---------+---------+--------------------+----------------+-----------------+
|adm1_name|adm2_name|           adm3_name|         quadkey|         HH_Count|
+---------+---------+--------------------+----------------+-----------------+
|Khon Kaen|Wiang Kao|Mueang Kao Phatthana|1322120010111102|872.0806118569035|
+---------+---------+--------------------+----------------+-----------------+

In [54]:
Matchinh_truth_set_71.toPandas().to_csv('Matchinh_truth_set_71.csv', index=False)

## Combining all Thailand

In [52]:

def to_snake_case(col):
    return lower(
        regexp_replace(col, r'[^a-zA-Z0-9]+', '_')
    )

In [ ]:
df_5_provinces = spark.read.parquet('/home/azureuser/prathyusha/Kearney/prathyusha/EDA/selected_5_province_HH_estimates.parquet')
df_5_provinces.show()

In [48]:
df_final = Matchinh_truth_set_71.unionByName(df_5_provinces)

df_final = df_final.withColumn('adm3_name', to_snake_case(col('adm3_name')))
df_final = df_final.withColumn('adm2_name', to_snake_case(col('adm2_name')))
df_final = df_final.withColumn('adm1_name', to_snake_case(col('adm1_name')))
df_final.count()

977366

In [49]:
df_final.show()

+---------+------------+-----------+----------------+------------------+
|adm1_name|   adm2_name|  adm3_name|         quadkey|          HH_Count|
+---------+------------+-----------+----------------+------------------+
| buri_ram|lam_plai_mat| khok_sa_at|1322120300123002|0.5958331335966651|
| buri_ram|lam_plai_mat| khok_sa_at|1322120300123300|0.7658522226010662|
| buri_ram|lam_plai_mat|mueang_faek|1322120300131003|1.1668015776724898|
| buri_ram|lam_plai_mat|     bu_pho|1322120300132201| 35.96388227477043|
| buri_ram|lam_plai_mat|     bu_pho|1322120300132230|1.5317887547621196|
| buri_ram|lam_plai_mat|mueang_faek|1322120300133222|1.6409855152091184|
| buri_ram|lam_plai_mat|   hin_khon|1322120300211211| 2.803688438722988|
| buri_ram|lam_plai_mat|phathai_rin|1322120300223322| 4.897439128893392|
| buri_ram|lam_plai_mat|   hin_khon|1322120300231001|13.638250461343143|
| buri_ram|lam_plai_mat|   hin_khon|1322120300231011|22.756942549606958|
| buri_ram|lam_plai_mat|phathai_rin|1322120300232321| 34.90536818316841|
| buri_ram|lam_plai_mat| khok_klang|1322120300233113|124.84705011155535|
| buri_ram|lam_plai_mat| khok_klang|1322120300233131| 4.261374209924712|
| buri_ram|lam_plai_mat|   khok_lam|1322120300300003|101.54059780374972|
| buri_ram|lam_plai_mat|   khok_lam|1322120300300212|14.538764699266764|
| buri_ram|lam_plai_mat|   hin_khon|1322120300302020| 1.358758738826859|
| buri_ram|lam_plai_mat|   hin_khon|1322120300302220|40.078039724733976|
| buri_ram|lam_plai_mat|   nong_khu|1322120300302330| 4.252945632330382|
| buri_ram|lam_plai_mat| thamenchai|1322120300312113| 2.951944406455603|
| buri_ram|lam_plai_mat| thamenchai|1322120300313122|1.6788374023596628|
+---------+------------+-----------+----------------+------------------+
only showing top 20 rows

In [55]:
bangkok = spark.read.parquet("abfss://propheus-data-science@propheusdatabay.dfs.core.windows.net/Thailand/bangkok/quadkey_level_household_estimates/")
bangkok = bangkok.drop('province_en')
bangkok = bangkok.withColumnRenamed('total_estimated_households_adjusted', 'HH_Count')
bangkok.show()

+---------+----------------+---------+---------+--------+
|adm2_name|         quadkey|adm3_name|adm1_name|HH_Count|
+---------+----------------+---------+---------+--------+
|  bang_na|1322033110221100|  bang_na|  bangkok|    1531|
|  bang_na|1322033110203303|  bang_na|  bangkok|     879|
|  bang_na|1322033110203230|  bang_na|  bangkok|    9671|
|  bang_na|1322033110212223|  bang_na|  bangkok|     698|
|  bang_na|1322033110203222|  bang_na|  bangkok|     956|
|  bang_na|1322033110203212|  bang_na|  bangkok|    1181|
|  bang_na|1322033110203232|  bang_na|  bangkok|    2124|
|  bang_na|1322033110203320|  bang_na|  bangkok|     920|
|  bang_na|1322033110221012|  bang_na|  bangkok|    2263|
|  bang_na|1322033110203323|  bang_na|  bangkok|     658|
|  bang_na|1322033110202333|  bang_na|  bangkok|     353|
|  bang_na|1322033110221000|  bang_na|  bangkok|     613|
|  bang_na|1322033110230002|  bang_na|  bangkok|     679|
|  bang_na|1322033110221013|  bang_na|  bangkok|    2582|
|  bang_na|1322033110221102|  bang_na|  bangkok|    1184|
|  bang_na|1322033110221101|  bang_na|  bangkok|     833|
|  bang_na|1322033110221113|  bang_na|  bangkok|    2478|
|  bang_na|1322033110221130|  bang_na|  bangkok|     413|
|  bang_na|1322033110203330|  bang_na|  bangkok|    1191|
|  bang_na|1322033110221103|  bang_na|  bangkok|     685|
+---------+----------------+---------+---------+--------+
only showing top 20 rows

In [56]:
df_final_final = df_final.unionByName(bangkok)
df_final_final.count()

981791

In [57]:
df_final_final.select('quadkey', 'adm3_name', 'adm2_name', 'adm1_name').distinct().count()

977153

In [100]:
df_final_final_final = df_final_final.groupBy('quadkey', 'adm3_name', 'adm2_name', 'adm1_name').agg(sum('HH_Count').alias('HH_Count'))
df_final_final_final = df_final_final_final.withColumn('HH_Count',when(col('quadkey') == '1322033110000021',10527).otherwise(col('HH_Count')))
df_final_final_final = df_final_final_final.withColumn('HH_Count',when(col('quadkey') == '1322033110320302',103).otherwise(col('HH_Count')))
df_final_final_final.count()

981418

In [101]:
df_final_final_final.select('quadkey', 'adm3_name', 'adm2_name', 'adm1_name').distinct().count()

981418

In [102]:
df_final_final_final = df_final_final_final.filter(col('HH_Count') > 0)
df_final_final_final = df_final_final_final.withColumn('HH_Count', ceil(col('HH_Count')))
df_final_final_final.toPandas().describe()

            HH_Count
count  981037.000000
mean       26.989265
std       111.061506
min         1.000000
25%         2.000000
50%         5.000000
75%        21.000000
max     11787.000000

In [103]:
df_final_final_final.count()

981037

In [104]:
df_final_final_final.toPandas().to_csv('Thailand_HH_Count.csv', index=False)

In [106]:
df_final_final_final.select(sum('HH_Count')).show()

+-------------+
|sum(HH_Count)|
+-------------+
|     26477468|
+-------------+

In [91]:
df_final_final_final.toPandas()['HH_Count'].describe()

count    981418.000000
mean         26.489837
std         111.054433
min           0.000000
25%           1.520495
50%           4.466675
75%          20.509905
max       11787.000000
Name: HH_Count, dtype: float64

In [92]:
df_final_final_final.select('adm1_name','adm2_name','adm3_name').distinct().count()

7417

In [93]:
df_final_final_final.select(sum('HH_Count')).show()

+--------------------+
|       sum(HH_Count)|
+--------------------+
|2.5997603172088426E7|
+--------------------+

In [94]:
df_final_final_final.toPandas().isna().sum()

quadkey      0
adm3_name    0
adm2_name    0
adm1_name    0
HH_Count     0
dtype: int64

In [61]:
df_final_final_final.show()

+----------------+--------------+--------------+------------+------------------+
|         quadkey|     adm3_name|     adm2_name|   adm1_name|          HH_Count|
+----------------+--------------+--------------+------------+------------------+
|1322120300312333|    thamenchai|  lam_plai_mat|    buri_ram|10.571285846115003|
|1322120300323213| nong_bua_khok|  lam_plai_mat|    buri_ram|0.5925368108237239|
|1322120300300232|      khok_lam|  lam_plai_mat|    buri_ram|0.6238949941687498|
|1322120300132231|        bu_pho|  lam_plai_mat|    buri_ram|1.1184703548448311|
|1322120300301130|     talat_pho|  lam_plai_mat|    buri_ram|0.8338654743656927|
|1322120300313032|    thamenchai|  lam_plai_mat|    buri_ram| 83.55429360407037|
|1322120300123012|    khok_sa_at|  lam_plai_mat|    buri_ram|0.7891076394048853|
|1322120300121313|    khok_sa_at|  lam_plai_mat|    buri_ram|3.9898632074513287|
|1322120302000313|   phathai_rin|  lam_plai_mat|    buri_ram|2.0713947517102063|
|1322120300231132|  lam_plai_mat|  lam_plai_mat|    buri_ram| 55.53446589317017|
|1322120300211113|      khok_lam|  lam_plai_mat|    buri_ram|0.6354095518868579|
|1322120300310312|   mueang_faek|  lam_plai_mat|    buri_ram|1.6358312166117224|
|1322120302101003|    khok_klang|  lam_plai_mat|    buri_ram|56.065415326904564|
|1322120320231032| non_din_daeng| non_din_daeng|    buri_ram|0.6101947390702727|
|1322120320232000| non_din_daeng| non_din_daeng|    buri_ram| 69.21069182364498|
|1322033111001033|  don_chimphli|bang_nam_priao|chachoengsao| 4.840479501600541|
|1322033111012223|bang_nam_priao|bang_nam_priao|chachoengsao|113.83777938122113|
|1322033111020330|    sala_daeng|bang_nam_priao|chachoengsao| 65.75948082773496|
|1322031333323121|       yothaka|bang_nam_priao|chachoengsao|32.388460960385565|
|1322033111003312|  don_chimphli|bang_nam_priao|chachoengsao|1.5159727583152056|
+----------------+--------------+--------------+------------+------------------+
only showing top 20 rows

In [74]:
df_final_final_final.select('quadkey').distinct().count()

981418

In [ ]:
df_final_final_final = df_final_final_final.filter(col('HH_Count') > 0)
df_final_final_final = df_final_final_final.withColumn('HH_Count', col('HH_Count').cast('integer'))
df_final_final_final = df_final_final_final.filter(col('HH_Count') > 0)
df_final_final_final.toPandas().describe()

            HH_Count
count  845295.000000
mean       30.193314
std       121.287899
min         1.000000
25%         2.000000
50%         6.000000
75%        25.000000
max     19844.000000

In [78]:
df_final_final_final.orderBy(col('HH_Count').desc()).show()

+----------------+-------------------+-------------------+------------+--------+
|         quadkey|          adm3_name|          adm2_name|   adm1_name|HH_Count|
+----------------+-------------------+-------------------+------------+--------+
|1322033110000021|            ban_mai|           pak_kret|  nonthaburi|   19844|
|1322033110320302|       bang_chalong|          bang_phli|samut_prakan|   12345|
|1322033110022233|        huai_khwang|        huai_khwang|     bangkok|   11787|
|1322033110201222|       phra_khanong|        khlong_toei|     bangkok|   10176|
|1322033101310233|        dao_khanong|          thon_buri|     bangkok|    9891|
|1322033110000001|            ban_mai|           pak_kret|  nonthaburi|    9867|
|1322033110203230|            bang_na|            bang_na|     bangkok|    9671|
|1322031332201302|       khlong_nueng|       khlong_luang|pathum_thani|    9075|
|1322033101310231|         talat_phlu|          thon_buri|     bangkok|    8894|
|1322031323322213|     bang_bua_thong|     bang_bua_thong|  nonthaburi|    8834|
|1322033110310221|           thap_yao|        lat_krabang|     bangkok|    8706|
|1322033110022120|          din_daeng|          din_daeng|     bangkok|    8488|
|1322033101132122|         bang_bamru|         bang_phlat|     bangkok|    8366|
|1322033110222111|            pak_nam|mueang_samut_prakan|samut_prakan|    8141|
|1322033110022123|        huai_khwang|        huai_khwang|     bangkok|    8017|
|1322033110022232|           makkasan|        ratchathewi|     bangkok|    7955|
|1322033101113211|         bang_kraso|  mueang_nonthaburi|  nonthaburi|    7950|
|1322033110122220|khlong_song_ton_nun|        lat_krabang|     bangkok|    7840|
|1322033101313112|        chong_nonsi|           yan_nawa|     bangkok|    7621|
|1322033101112133|         bang_kraso|  mueang_nonthaburi|  nonthaburi|    7471|
+----------------+-------------------+-------------------+------------+--------+
only showing top 20 rows

In [80]:
from utils import *

In [82]:
@udf(StringType())
def quadkey_to_wkt_geometry(qk):
    import mercantile
    from shapely.geometry import shape
    if not qk:
        return None
    try:

        tile_feature = mercantile.feature(mercantile.quadkey_to_tile(qk))
        return shape(tile_feature['geometry']).wkt
    except:
        return None

In [83]:
df_final_final_final = df_final_final_final.withColumn('quadkey_geometry', quadkey_to_wkt_geometry('quadkey'))
df_final_final_final.show()

+----------------+--------------+--------------+------------+--------+--------------------+
|         quadkey|     adm3_name|     adm2_name|   adm1_name|HH_Count|    quadkey_geometry|
+----------------+--------------+--------------+------------+--------+--------------------+
|1322120300312333|    thamenchai|  lam_plai_mat|    buri_ram|      10|POLYGON ((102.958...|
|1322120300132231|        bu_pho|  lam_plai_mat|    buri_ram|       1|POLYGON ((102.936...|
|1322120300313032|    thamenchai|  lam_plai_mat|    buri_ram|      83|POLYGON ((102.974...|
|1322120300121313|    khok_sa_at|  lam_plai_mat|    buri_ram|       3|POLYGON ((102.914...|
|1322120302000313|   phathai_rin|  lam_plai_mat|    buri_ram|       2|POLYGON ((102.694...|
|1322120300231132|  lam_plai_mat|  lam_plai_mat|    buri_ram|      55|POLYGON ((102.821...|
|1322120300310312|   mueang_faek|  lam_plai_mat|    buri_ram|       1|POLYGON ((102.952...|
|1322120302101003|    khok_klang|  lam_plai_mat|    buri_ram|      56|POLYGON ((102.881...|
|1322120320232000| non_din_daeng| non_din_daeng|    buri_ram|      69|POLYGON ((102.744...|
|1322033111001033|  don_chimphli|bang_nam_priao|chachoengsao|       4|POLYGON ((100.958...|
|1322033111012223|bang_nam_priao|bang_nam_priao|chachoengsao|     113|POLYGON ((100.991...|
|1322033111020330|    sala_daeng|bang_nam_priao|chachoengsao|      65|POLYGON ((100.931...|
|1322031333323121|       yothaka|bang_nam_priao|chachoengsao|      32|POLYGON ((101.145...|
|1322033111003312|  don_chimphli|bang_nam_priao|chachoengsao|       1|POLYGON ((100.975...|
|1322033111012012|     mon_thong|bang_nam_priao|chachoengsao|       4|POLYGON ((100.997...|
|1322122002030130| nong_mai_kaen|    plaeng_yao|chachoengsao|      11|POLYGON ((101.370...|
|1322122002000111|      wang_yen|    plaeng_yao|chachoengsao|      54|POLYGON ((101.288...|
|1322122002013320| nong_mai_kaen|    plaeng_yao|chachoengsao|       2|POLYGON ((101.403...|
|1322122000223113|   hua_samrong|    plaeng_yao|chachoengsao|      70|POLYGON ((101.332...|
|1322122002012030|      wang_yen|    plaeng_yao|chachoengsao|      21|POLYGON ((101.348...|
+----------------+--------------+--------------+------------+--------+--------------------+
only showing top 20 rows

In [84]:
df_final_final_final.orderBy(col('HH_Count').desc()).show()

+----------------+-------------------+-------------------+------------+--------+--------------------+
|         quadkey|          adm3_name|          adm2_name|   adm1_name|HH_Count|    quadkey_geometry|
+----------------+-------------------+-------------------+------------+--------+--------------------+
|1322033110000021|            ban_mai|           pak_kret|  nonthaburi|   19844|POLYGON ((100.552...|
|1322033110320302|       bang_chalong|          bang_phli|samut_prakan|   12345|POLYGON ((100.744...|
|1322033110022233|        huai_khwang|        huai_khwang|     bangkok|   11787|POLYGON ((100.563...|
|1322033110201222|       phra_khanong|        khlong_toei|     bangkok|   10176|POLYGON ((100.590...|
|1322033101310233|        dao_khanong|          thon_buri|     bangkok|    9891|POLYGON ((100.475...|
|1322033110000001|            ban_mai|           pak_kret|  nonthaburi|    9867|POLYGON ((100.552...|
|1322033110203230|            bang_na|            bang_na|     bangkok|    9671|POLYGON ((100.601...|
|1322031332201302|       khlong_nueng|       khlong_luang|pathum_thani|    9075|POLYGON ((100.612...|
|1322033101310231|         talat_phlu|          thon_buri|     bangkok|    8894|POLYGON ((100.475...|
|1322031323322213|     bang_bua_thong|     bang_bua_thong|  nonthaburi|    8834|POLYGON ((100.387...|
|1322033110310221|           thap_yao|        lat_krabang|     bangkok|    8706|POLYGON ((100.816...|
|1322033110022120|          din_daeng|          din_daeng|     bangkok|    8488|POLYGON ((100.568...|
|1322033101132122|         bang_bamru|         bang_phlat|     bangkok|    8366|POLYGON ((100.480...|
|1322033110222111|            pak_nam|mueang_samut_prakan|samut_prakan|    8141|POLYGON ((100.585...|
|1322033110022123|        huai_khwang|        huai_khwang|     bangkok|    8017|POLYGON ((100.574...|
|1322033110022232|           makkasan|        ratchathewi|     bangkok|    7955|POLYGON ((100.557...|
|1322033101113211|         bang_kraso|  mueang_nonthaburi|  nonthaburi|    7950|POLYGON ((100.519...|
|1322033110122220|khlong_song_ton_nun|        lat_krabang|     bangkok|    7840|POLYGON ((100.722...|
|1322033101313112|        chong_nonsi|           yan_nawa|     bangkok|    7621|POLYGON ((100.535...|
|1322033101112133|         bang_kraso|  mueang_nonthaburi|  nonthaburi|    7471|POLYGON ((100.497...|
+----------------+-------------------+-------------------+------------+--------+--------------------+
only showing top 20 rows

In [ ]:
df_final_final_final.filter(col('HH_Count'))

## Validations

In [11]:
District_HH_count = Matchinh_truth_set.groupBy('adm1_name', 'adm2_name').agg(
    sum('Truthset_estimated_HH_count').alias('Truthset_estimated_HH_count')
)
District_HH_count.show()

+-------------------+-----------------+---------------------------+
|          adm1_name|        adm2_name|Truthset_estimated_HH_count|
+-------------------+-----------------+---------------------------+
|          Bueng Kan|     Phon Charoen|          12457.64846471362|
|           Buri Ram|          Krasang|         24955.945337244244|
|           Buri Ram|     Lam Plai Mat|         32837.496833696394|
|           Buri Ram|    Non Din Daeng|          8923.438505503214|
|       Chachoengsao|   Bang Nam Priao|         38398.099432736635|
|       Chachoengsao|       Plaeng Yao|         23142.965758187805|
|         Chiang Rai|        Doi Luang|          7229.027072022763|
|         Chiang Rai|     Mae Fa Luang|          27526.35061722876|
|         Chiang Rai|          Pa Daet|          9195.349528808569|
|            Kalasin|         Don Chan|          5217.434431561696|
|            Kalasin|       Yang Talat|          37326.48097030411|
|     Kamphaeng Phet|  Pang Sila Thong|         10281.273160804403|
|       Kanchanaburi|   Thong Pha Phum|         23219.275116485394|
|          Khon Kaen|         Ban Phai|          40692.49001216753|
|               Loei|         Nong Hin|          7031.709348684976|
|           Lop Buri|     Khok Charoen|           9852.48751115793|
|      Maha Sarakham|     Yang Sisurat|         10958.020443892578|
|  Nakhon Ratchasima|        Ban Lueam|          7611.667159728442|
|  Nakhon Ratchasima|      Chum Phuang|         27386.636537264167|
|Nakhon Si Thammarat|Chaloem Phra Kiat|         11794.731511262438|
+-------------------+-----------------+---------------------------+
only showing top 20 rows

In [12]:
estm_province_hh = District_HH_count.groupBy('adm1_name').agg(sum('Truthset_estimated_HH_count').alias('Truthset_estimated_HH_count'))
estm_province_hh.show()

+-------------------+---------------------------+
|          adm1_name|Truthset_estimated_HH_count|
+-------------------+---------------------------+
|       Chachoengsao|          354958.4279098904|
|        Phitsanulok|         381686.96170950506|
|         Narathiwat|          197925.3528553552|
|         Phetchabun|          335624.7126000605|
|     Kamphaeng Phet|          287030.1425312369|
|      Maha Sarakham|          309884.0630748085|
|                Tak|         189426.87162253424|
|Nakhon Si Thammarat|         523908.58598581306|
|        Phatthalung|         175160.33220115537|
|          Khon Kaen|           678663.371119605|
|             Roi Et|         367345.89397383056|
|           Lop Buri|         307311.81893243134|
|         Chiang Rai|          430866.6011265144|
|               Trat|         110040.22852363532|
|          Sukhothai|         244251.83209032303|
|        Surat Thani|           429399.212832271|
|   Ubon Ratchathani|          605607.6498995676|
|           Songkhla|          608772.5448380926|
|        Phetchaburi|         192298.87836855193|
|          Bueng Kan|         116377.32620138576|
+-------------------+---------------------------+
only showing top 20 rows

In [14]:
nso_hh_count = spark.read.csv('/home/azureuser/prathyusha/Kearney/prathyusha/EDA/pop_hhcount_nso_w_geom.csv', header=True).select(
    'Province', '2022_HH_count'
)
nso_hh_count.show()

+--------------------+-------------+
|            Province|2022_HH_count|
+--------------------+-------------+
|             bangkok|      3369140|
|         samutprakan|       924779|
|          nonthaburi|       608941|
|         pathumthani|       675573|
|phranakhonsiayutt...|       311101|
|            angthong|        82287|
|             lopburi|       266958|
|            singburi|        62131|
|             chainat|       101490|
|            saraburi|       253998|
|            chonburi|       690875|
|              rayong|       401393|
|         chanthaburi|       190627|
|                trat|        97383|
|        chachoengsao|       318295|
|         prachinburi|       249575|
|         nakhonnayok|        88356|
|              sakaeo|       212976|
|          ratchaburi|       250405|
|        kanchanaburi|       260639|
+--------------------+-------------+
only showing top 20 rows

In [15]:
final_province_check = estm_province_hh.join(
    nso_hh_count,
    regexp_replace(lower(estm_province_hh.adm1_name), " ", "") == nso_hh_count.Province,
    how = 'inner'
)
final_province_check.count()

71

In [ ]:
final_province_check_pd = final_province_check.toPandas()

         adm1_name  Truthset_estimated_HH_count       Province 2022_HH_count
0     Chachoengsao                354958.427910   chachoengsao        318295
1      Phitsanulok                381686.961710    phitsanulok        323784
2       Narathiwat                197925.352855     narathiwat        181888
3       Phetchabun                335624.712600     phetchabun        292360
4   Kamphaeng Phet                287030.142531  kamphaengphet        253396
..             ...                          ...            ...           ...
66        Mukdahan                150510.762869       mukdahan        132432
67    Mae Hong Son                 95524.941337     maehongson         81739
68   Nakhon Phanom                200542.783051   nakhonphanom        173917
69           Krabi                147395.817389          krabi        132475
70        Chumphon                189854.948297       chumphon        169702

[71 rows x 4 columns]

In [18]:
final_province_check_pd.dtypes

adm1_name                       object
Truthset_estimated_HH_count    float64
2022_HH_count                   object
dtype: object

In [20]:
# final_province_check_pd = final_province_check_pd.drop(columns={'Province'})
final_province_check_pd['2022_HH_count'] = final_province_check_pd['2022_HH_count'].astype(int)
final_province_check_pd['%_diff'] = (final_province_check_pd['Truthset_estimated_HH_count'] - final_province_check_pd['2022_HH_count']) * 100/final_province_check_pd['2022_HH_count']
final_province_check_pd

         adm1_name  Truthset_estimated_HH_count  2022_HH_count     %_diff
0     Chachoengsao                354958.427910         318295  11.518694
1      Phitsanulok                381686.961710         323784  17.883207
2       Narathiwat                197925.352855         181888   8.817158
3       Phetchabun                335624.712600         292360  14.798438
4   Kamphaeng Phet                287030.142531         253396  13.273352
..             ...                          ...            ...        ...
66        Mukdahan                150510.762869         132432  13.651355
67    Mae Hong Son                 95524.941337          81739  16.865806
68   Nakhon Phanom                200542.783051         173917  15.309477
69           Krabi                147395.817389         132475  11.263119
70        Chumphon                189854.948297         169702  11.875493

[71 rows x 4 columns]

In [21]:
final_province_check_pd['%_diff'].describe()

count    71.000000
mean     13.599212
std       2.592892
min       7.392183
25%      11.844447
50%      13.563154
75%      14.902295
max      21.086709
Name: %_diff, dtype: float64